"""empty message

Revision ID: 56b85256f3c2
Revises: 
Create Date: 2020-02-14 15:21:08.432647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56b85256f3c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('casino', sa.String(length=40), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('h1', sa.String(length=200), nullable=True),
    sa.Column('buy_in', sa.String(length=20), nullable=True),
    sa.Column('blinds', sa.String(length=20), nullable=True),
    sa.Column('starting_stack', sa.String(length=20), nullable=True),
    sa.Column('results_link', sa.String(length=500), nullable=True),
    sa.Column('structure_link', sa.String(length=500), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=3000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournaments')
    # ### end Alembic commands ###
